using System;
using System.Collections.Generic;
using System.Text;

namespace FnacDarty.JobInterview.Stock.Core.Entities
{
    /// <summary>
    /// Describes a flow
    /// </summary>
    public class Flow
    {
        /// <summary>
        /// An autogenerated identifier
        /// </summary>
        public Guid Id { get; } = Guid.NewGuid();

        /// <summary>
        /// The movement date
        /// </summary>
        public DateTime Date { get; set; }

        /// <summary>
        /// The movement label
        /// </summary>
        public string Label { get; set; }

        /// <summary>
        /// indicates if the flow is a regularization flow
        /// </summary>
        public bool IsRegularizationFlow { get; set; }

        /// <summary>
        /// The list of <see cref="ProductLine"/> informations
        /// </summary>
        public List<ProductLine> FlowLines { get; set; }
    }
}
